---
- name: Backup and update ini.conf file
  hosts: all
  become: yes
  vars:
    original_file_path: /home/pawas/testing/ini.conf
    backup_file_prefix: /home/pawas/testing/ini.conf_backup
    new_config_url: https://raw.githubusercontent.com/fawwaz26/ansible-fluentd/main/ini.conf

  tasks:
    - name: Backup original ini.conf file
      ansible.builtin.copy:
        src: "{{ original_file_path }}"
        dest: "{{ backup_file_prefix }}.conf"
        remote_src: yes
      become: yes

    - name: Download and replace ini.conf with the new file
      ansible.builtin.get_url:
        url: "{{ new_config_url }}"
        dest: "{{ original_file_path }}"
        mode: '0644'
      become: yes
