---
- name: Update and backup ini.conf file
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get current timestamp
      command: date +%Y%m%d%H%M%S
      register: current_time

    - name: Check if ini.conf exists
      stat:
        path: /home/pawas/testing/ini.conf
      register: ansible_stat

    - name: Backup existing ini.conf file
      copy:
        src: /home/pawas/testing/ini.conf
        dest: "/home/pawas/testing/ini.conf_backup{{ current_time.stdout }}"
        remote_src: yes
      when: ansible_stat.stat.exists

    - name: Download new ini.conf file
      get_url:
        url: https://raw.githubusercontent.com/fawwaz26/ansible-fluentd/main/ini.conf
        dest: /home/pawas/testing/ini.conf
