---
- name: Backup and update ini.conf file
  hosts: all
  become: yes
  vars:
    original_file_path: /home/user/testing/ini.conf
    backup_file_prefix: /home/user/testing/ini.conf_backup
    new_config_url: https://github.com/fawwaz26/ansible-fluentd/blob/main/ini.conf

  tasks:
    - name: Get current timestamp
      ansible.builtin.command: "date +%Y%m%d%H%M%S"
      register: current_time

    - name: Backup original ini.conf file
      ansible.builtin.copy:
        src: "{{ original_file_path }}"
        dest: "{{ backup_file_prefix }}_{{ current_time.stdout }}.conf"
        remote_src: yes
      become: yes

    - name: Download and replace ini.conf with the new file
      ansible.builtin.get_url:
        url: "{{ new_config_url }}"
        dest: "{{ original_file_path }}"
        mode: '0644'
      become: yes
