---
- name: Konfigurasi TD-Agent Fluentd
  hosts: all
  vars:
    timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
  tasks:
    - name: Backup file ini.conf yang lama dengan timestamp
      ansible.builtin.copy:
        src: /etc/td-agent/td-agent.conf
        dest: "/etc/td-agent/td-agent.conf.backup-{{ timestamp }}"
        remote_src: yes
      become: yes

    - name: Download dan ganti file ini.conf dengan versi baru
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/fawwaz26/ansible-fluentd/main/td-agent.conf
        dest: /etc/td-agent/td-agent.conf
        force: yes
      become: yes
