---
- name: Backup and Replace File
  hosts: your_target_host
  tasks:
    - name: Backup the original ini.conf file
      ansible.builtin.copy:
        src: /home/pawas/testing/ini.conf
        dest: /home/pawas/testing/ini.conf.backup
        remote_src: yes
      become: yes

    - name: Replace ini.conf with the new file
      ansible.builtin.copy:
        src: /path/to/your/new/ini.conf
        dest: /home/pawas/testing/ini.conf
      become: yes
