---
- name: Manage and check status of td-agent service
  hosts: all
  become: yes
  tasks:
    - name: Gather the service facts
      service_facts:
    
    - name: Show td-agent service status before restart
      debug:
        msg: "td-agent service status: {{ ansible_facts.services['td-agent.service'].state }}"
    
    - name: Restart td-agent service
      service:
        name: td-agent
        state: restarted
      become: true
      register: restart_result

    - name: Show td-agent service status after restart
      debug:
        msg: "td-agent service status after restart: {{ restart_result.status }}"
